### ISSUE TITLE
Access to match history limited to the 10 last matchs maximum

### ISSUE THREAD

**Issue by agrenier-gnss** [raimannma/ValorantAPI#181]
Hi everyone, 

Not sure if it is a bug report or a limitation of the RIOT API, but I will put it as a bug report. 

## 🐛 Bug Report

It seems only the last 10 match in Match History can be accessed when using `valo_api.endpoints.get_match_history_by_name_v3`.

## 🔬 How To Reproduce

Use size >= 10 in function, only the last 10 matches are retrieved. 

### Code sample

Called `valo_api.endpoints.get_match_history_by_name_v3([REGION], [PLAYER], [TAG], size=100)`

### Environment

* OS: Linux 
* Python version, get it with: 3.8.10 

## 📈 Expected behavior

In other trackers online they seem to have more matches available, so I would guess those information are still RIOT database and should be accessible through the API?

Thanks you for your help and for the library!

**Comment by raimannma** [comment]
Hey, thanks for your issue.

This is not a problem with my wrapper but with the api.

The match history endpoint from henriks api is limited to 10 matches currently. We are also working on a pagination solution to support more matches.

But there is still a way for you to get more matches than the last 10. You can use the raw match history endpoint. This endpoint returns a list of match ids and supports pagination. After you collected all the match ids you can use the get match details endpoint to retrieve all match data.

Small Code Example:
```python
    def get_matches(cls, region: str, puuid: str) -> List[MatchHistoryPointV3]:
        step_size = 20  # maximum is 20

        match_ids = set()
        query_args = {
            "startIndex": 0,
            "endIndex": step_size,
        }
        while True:
            match_history = valo_api.get_raw_data_v1(EndpointType.MATCH_HISTORY, region=region, value=puuid, queries=query_args)
            for match in match_history.History:
                if match.QueueID == "competitive":
                    match_ids.add(match.MatchID)

            if query_args["endIndex"] >= match_history.Total:
                # All matches processed
                break
            # Update query args. Do the next pagination step.
            query_args["startIndex"] = query_args["endIndex"] + 1
            query_args["endIndex"] = min(query_args["startIndex"] + step_size, match_history.Total)

        return [cls.get_match_details(match_id) for match_id in match_ids]
```

This code snippet will get all the matches available. but you should stop the while loop after you got all the competitive matches you need.

**Comment by raimannma** [comment]
I added the documentation tag, cause this is can be better documented

**Comment by agrenier-gnss** [comment]
Hey!

Ok I understand, the snippet is a good way around, I'll use that in the meantime.

Thanks you the reply and for this wrapper!
Regards.

**Comment by carlosbrown2** [comment]
I have recently run into the same issue, this is helpful, thank you @raimannma

**Comment by raimannma** [comment]
I will add an assert statement, to prohibit any higher size than 10, and will link tot this issue.

**Comment by carlosbrown2** [comment]
@raimannma Using the above approach does allow me to obtain more than just the last ten matches, however it still caps the number of matches I can retrieve at an arbitrary number. It does not return the full match history for a given player. Is there a known reason why it would still be limiting how many matches you can see? 

For the players whose match history I want, it returns somewhere on the order from their last 50 - 80 matches, using a basic API key. We know that these players have played many more matches than what is retrieved.

**Comment by raimannma** [comment]
Yeah riot doesn't provide more than the given match history. I don't think that there is a way to fetch more matches in the past. Maybe you could ask Henrik from the unofficial API (Linked in the readme), he has way more matches stored on his server so he maybe is able to provide a longer history.
